name: İnfrastructure Pipeline

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'infrastructure/**'

  pull_request:
    paths:
      - 'infrastructure/**'

## bu workflowun github tarafındaki yetkileri
## id-token , workflowa OIDC kimlik tokenı isteme-ürettirme izni verir.
## contents, workflowun repositorydeki dosyaları okuma izni verir.
permissions:
  id-token: write
  contents: read

jobs:
  plan:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name : Setup Terraform 
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.16.2
          terraform_wrapper: false

      - name: Setup Terragrunt
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: 0.82.2
          tf_path: terraform

      - name: Azure login
        uses: azure/login@v3
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          mask-client-id: false

      - name: Run terragrunt plan
        working-directory: infrastructure/env/dev
        run: terragrunt run --all plan
## bağımlılıklardan dolayı terragrunt plan kısmı da çalışmıyor 

  apply:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name : Setup Terraform 
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.16.2
          terraform_wrapper: false

      - name: Setup Terragrunt
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: 0.82.2
          tf_path: terraform

      - name: Azure Login
        uses: azure/login@v3
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          mask-client-id: false

      - name: Terragrunt Apply
        working-directory: infrastructure/env/dev
        run: terragrunt run --all apply -- -auto-approve

